# Generated by Django 3.2.6 on 2022-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='http://cdn.onlinewebfonts.com/svg/img_191958.png', null=True),
        ),
    ]
