# Generated by Django 3.2.6 on 2022-06-20 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
