# Generated by Django 3.2.6 on 2022-06-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220621_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='web.tag'),
        ),
    ]
